### ISSUE TITLE
serverless freamworkでローカルでラムダをテスト

### ISSUE THREAD

**Issue by Khanashima** [Khanashima/study-serverless#11]

**Comment by Khanashima** [comment]
## 前提条件

ローカルでAPI GateWayとLambdaを実施するためにはServerless Frameworkのserverless-offlineプラグインを使用する。

## 手順

手順1.serverless-offlineのインストール
npm install --save-dev serverless-offline

手順2.設定ファイルのserverless.tsでプラグインでserverless-offlineを使用することを追加する
```
  plugins: ['serverless-esbuild', 'serverless-offline'],
```

手順3. オフラインモードで起動
```
sls offline start
```

以下のようにローカル環境が立ち上がる
```
   POST | http://localhost:3000/dev/hello                                  │
   │   POST | http://localhost:3000/2015-03-31/functions/hello/invocations     │
   │   GET  | http://localhost:3000/dev/user                                   │
   │   POST | http://localhost:3000/2015-03-31/functions/getUser/invocations   
```

手順4. curl等でAPIを叩く

**Comment by bellshun** [comment]
課題：middyでJestのテストコードを書く方法
インストール -> jest.config.js作成 -> __tests__フォルダにhello.spec.tsを作成までは把握
middyでラップされたコードのテスト方法が不明

**Comment by bellshun** [comment]
middyfyを以下のようにmock化することでhandler内のテストは成功（他にやっている記事がないので正しいかは不明）

https://github.com/nordcloud/serverless-jest-plugin
のリポジトリを参考にして、
@middy/coreというのがよくわからなかったので@libs/lambdaのモックに変えたらいけた

```
jest.mock('@libs/lambda', () => ({
    middyfy: jest.fn((handler) => handler),
}));
```
