### ISSUE TITLE
ajvでバリデーション

### ISSUE THREAD

**Issue by Khanashima** [Khanashima/study-serverless#16]
ajvでバリデーションの参考
https://bokunonikki.net/post/2022/1012_typescript_ajv_validation/

**Comment by Khanashima** [comment]
ajvでバリデーションを対応
俺の記事
https://zenn.dev/kiiimii/articles/80895a26534595

**Comment by bellshun** [comment]
ajv.compileまたはvalidateはどこで実行するのでしょうか？
middyと違って各handler内で実行する必要がありますか？

**Comment by vfjhanashima** [comment]
@superherobtf1985

> ajv.compileまたはvalidateはどこで実行するのでしょうか？ middyと違って各handler内で実行する必要がありますか？

ajv.validateは各handler内で行います。
valid = ajv.validate(schema,event.body);
でバリデーションエラーの生データが返ってきます。
これを
解析用の共通メソッドでパースし、
validのデータからエラーレスポンスを作り、返します。
(バリデーションのデータのparams、messageからエラーレスポンスを作ります。)
